style changed with tailwind
evgenya2905/my-anime-app pull request #1
Opened 2024-08-16 19:01 UTC by evgenya2905

2024-08-18 08:25 UTC, EvgeniyHalimon requested changes

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/lib/components/Item.svelte
> -  /* import { page } from '$app/stores'; */
Удалить закоментированный код

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/lib/components/Item.svelte
> -  /* const handleGenreClick = (genreId: number, event: Event) => {
удалить закоментированный код

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/lib/components/ItemDetail.svelte
>    }
вместо any поставить акутальный типы/интерфейсы

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/lib/components/ItemDetail.svelte
> -  /* console.log(link); */
убрать закоментированное

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/+page.svelte
>    let items: Item[] = [];
изменить нейминг интерфейса

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/+page.svelte
> -    /* console.log('🚀 ~ getTopManga ~ data:', data); */
удалить все комменты

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/[slug]/+page.svelte
>  <!-- <ItemDetail
убрать комменты

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/anime/[slug]/+page.svelte
> -  /*  console.log('🚀 ~ page:', $page.params.slug); */
комменты

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/genre/+page.svelte
> -  /*  console.log('🚀 ~ page:', $page.url.pathname); */
комменты

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/genre/+page.svelte
>    let genresAnime: Genre[] = [];
поменять на IGenre если это интерфейс / поменять на GenreType если это тип

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/genre/anime/[slug]/+page.svelte
> -    /*  console.log(data);
комменты

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/genre/manga/[slug]/+page.svelte
> -  /* console.log('🚀 ~ page:', $page.params.slug); */
комменты

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/search/anime/+page.svelte
> -    /* console.log(items); */
комменты

2024-08-18 08:25 UTC, EvgeniyHalimon commented on src/routes/manga/[slug]/+page.svelte
> -  /* console.log('🚀 ~ page:', $page.params.slug); */
комменты

2024-08-19 10:28 UTC, evgenya2905 commented on src/lib/components/Item.svelte
> -  /* const handleGenreClick = (genreId: number, event: Event) => {
+

2024-08-19 10:28 UTC, evgenya2905 commented on src/lib/components/ItemDetail.svelte
> -  /* console.log(link); */
+

2024-08-19 10:33 UTC, evgenya2905 commented on src/routes/+page.svelte
>    let items: Item[] = [];
done

2024-08-19 10:33 UTC, evgenya2905 commented on src/routes/+page.svelte
> -    /* console.log('🚀 ~ getTopManga ~ data:', data); */
+

2024-08-19 10:39 UTC, evgenya2905 commented on src/routes/anime/[slug]/+page.svelte
> -  /*  console.log('🚀 ~ page:', $page.params.slug); */
Видалила все. Не потрібна сторінка в коді.

2024-08-19 10:40 UTC, evgenya2905 commented on src/routes/anime/[slug]/+page.svelte
> -  /*  console.log('🚀 ~ page:', $page.params.slug); */
Видалила все. Непотрібна сторінка в коді.

2024-08-19 10:41 UTC, evgenya2905 commented on src/routes/[slug]/+page.svelte
>  <!-- <ItemDetail
Видалила все. Непотрібна сторінка в коді.

2024-08-19 10:42 UTC, evgenya2905 commented on src/routes/anime/[slug]/+page.svelte
> -  /*  console.log('🚀 ~ page:', $page.params.slug); */
+

2024-08-19 10:42 UTC, evgenya2905 commented on src/routes/genre/+page.svelte
> -  /*  console.log('🚀 ~ page:', $page.url.pathname); */
+

2024-08-19 10:43 UTC, evgenya2905 commented on src/routes/genre/+page.svelte
>    let genresAnime: Genre[] = [];
done

2024-08-19 10:44 UTC, evgenya2905 commented on src/routes/genre/anime/[slug]/+page.svelte
> -    /*  console.log(data);
+

2024-08-19 10:45 UTC, evgenya2905 commented on src/routes/genre/manga/[slug]/+page.svelte
> -  /* console.log('🚀 ~ page:', $page.params.slug); */
+

2024-08-19 10:45 UTC, evgenya2905 commented on src/routes/search/anime/+page.svelte
> -    /* console.log(items); */
+

2024-08-19 10:46 UTC, evgenya2905 commented on src/routes/manga/[slug]/+page.svelte
> -  /* console.log('🚀 ~ page:', $page.params.slug); */
+

2024-08-19 10:46 UTC, evgenya2905 commented on src/lib/components/Item.svelte
> -  /* import { page } from '$app/stores'; */
+

2024-08-19 10:56 UTC, evgenya2905 commented on src/lib/components/ItemDetail.svelte
>    }
done

2024-08-19 19:05 UTC, EvgeniyHalimon approved these changes

2024-08-19 19:06 UTC, merged